import { getFileExtension } from "@arciin/shared"

/** Map file extension / name to a Shiki bundled language id. */
const EXT_TO_LANG: Record<string, string> = {
  py: "python",
  pyw: "python",
  pyi: "python",
  ipynb: "python",
  js: "javascript",
  mjs: "javascript",
  cjs: "javascript",
  ts: "typescript",
  tsx: "tsx",
  jsx: "jsx",
  json: "json",
  html: "html",
  htm: "html",
  css: "css",
  scss: "scss",
  sass: "sass",
  less: "less",
  vue: "vue",
  svelte: "svelte",
  go: "go",
  rs: "rust",
  java: "java",
  kt: "kotlin",
  kts: "kotlin",
  c: "c",
  cc: "cpp",
  cpp: "cpp",
  cxx: "cpp",
  h: "c",
  hpp: "cpp",
  cs: "csharp",
  php: "php",
  rb: "ruby",
  sh: "bash",
  bash: "bash",
  zsh: "bash",
  fish: "fish",
  ps1: "powershell",
  sql: "sql",
  yaml: "yaml",
  yml: "yaml",
  toml: "toml",
  xml: "xml",
  swift: "swift",
  r: "r",
  lua: "lua",
  pl: "perl",
  scala: "scala",
  zig: "zig",
  dart: "dart",
  ex: "elixir",
  exs: "elixir",
  erl: "erlang",
  hs: "haskell",
  clj: "clojure",
  cljs: "clojure",
  dockerfile: "docker",
  md: "markdown",
  markdown: "markdown",
  csv: "csv",
  tsv: "csv",
  log: "log",
  txt: "plaintext",
  env: "dotenv",
  ini: "ini",
  cfg: "ini",
  conf: "ini",
}

export function highlightLanguageFromFilename(filename: string): string {
  const base = filename.split(/[/\\]/).pop()?.toLowerCase() ?? ""
  if (base === "dockerfile") return "docker"
  if (base === "makefile") return "make"
  if (base.startsWith(".env")) return "dotenv"
  const ext = getFileExtension(filename).toLowerCase()
  return EXT_TO_LANG[ext] ?? "plaintext"
}
