import type { Metadata } from "next"
import Link from "next/link"

export const metadata: Metadata = {
  title: "Privacy Policy — Arciin",
  description: "How Arciin handles data on your self-hosted instance.",
}

export default function PrivacyPage() {
  return (
    <main className="min-h-svh bg-background px-6 py-12 text-zinc-400 sm:px-10 sm:py-16">
      <article className="mx-auto max-w-3xl">
        <nav className="mb-10 flex flex-wrap gap-x-4 gap-y-2 text-xs text-zinc-500">
          <Link href="/setup" className="hover:text-zinc-300 hover:underline">
            Back to setup
          </Link>
          <span aria-hidden className="text-zinc-700">
            |
          </span>
          <Link href="/legal/terms" className="hover:text-zinc-300 hover:underline">
            Terms of Use
          </Link>
        </nav>

        <header className="border-b border-white/10 pb-8">
          <h1 className="font-heading text-3xl font-semibold tracking-tight text-white sm:text-4xl">
            Privacy Policy
          </h1>
          <p className="mt-3 max-w-2xl text-sm leading-relaxed">
            This policy describes how the Arciin application processes information when you
            deploy and operate it on hardware you control. Arciin is self-hosted software: the
            operator of each deployment (for example, you or your organization) decides what is
            collected beyond what the software needs to function.
          </p>
          <p className="mt-4 text-xs leading-relaxed text-zinc-500">
            This document is provided as a starting point for self-hosted deployments. It is not
            legal advice. Consult qualified counsel for regulated or public-facing environments.
          </p>
        </header>

        <div className="space-y-10 py-10 text-sm leading-relaxed">
          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-white">1. Who this applies to</h2>
            <p>
              This Privacy Policy applies to end users of an Arciin instance and to the person or
              entity that installs, configures, and operates that instance (the &quot;operator&quot;).
              The operator is typically the data controller for information stored in Arciin. If
              you use someone else&apos;s instance, their practices may differ; ask them for their
              policy.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-white">2. What Arciin is</h2>
            <p>
              Arciin is private file, library, and media management software intended to run on a
              server you own or manage. It stores file binaries on disk (or connected storage) and
              metadata (such as accounts, libraries, asset records, activity, and jobs) in a
              database you configure. Network services (API, web UI, optional realtime channels)
              run according to your deployment choices.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-white">3. Information the software processes</h2>
            <p>Depending on how you use Arciin, the application may process categories such as:</p>
            <ul className="list-disc space-y-2 pl-5">
              <li>
                <span className="text-zinc-300">Account and authentication data</span> — for
                example name, email, role, password hashes, session identifiers, and API key
                metadata (not raw secrets where hashing applies).
              </li>
              <li>
                <span className="text-zinc-300">Content and technical metadata</span> — filenames,
                paths or internal keys you configure, MIME types, upload and processing status,
                thumbnails or previews generated by workers, and similar fields needed to operate
                libraries and uploads.
              </li>
              <li>
                <span className="text-zinc-300">Operational and security logs</span> — server or
                container logs generated by your environment may include request metadata, errors,
                or IP addresses depending on your logging configuration outside Arciin.
              </li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-white">4. Where data lives</h2>
            <p>
              Data remains on systems and storage locations you configure (for example local disks,
              attached volumes, or future integration backends you enable). Arciin does not require
              a hosted Arciin cloud account to operate the core product. If you enable remote access
              (reverse proxy, tunnel, or similar), traffic and logs may be visible to providers you
              choose.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-white">5. Cookies and sessions</h2>
            <p>
              The web application may use cookies or similar mechanisms for authenticated sessions
              (for example httpOnly session cookies). Scope and lifetime follow your server
              configuration and Arciin&apos;s session settings.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-white">6. Sharing and subprocessors</h2>
            <p>
              By default, Arciin does not send your libraries or personal data to Arciin as a
              hosted service because there is no required vendor cloud in the core self-hosted
              model. If you configure integrations (for example media tools, webhooks, or storage
              backends), those providers process data under their own terms and your configuration.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-white">7. Security</h2>
            <p>
              Arciin is designed with common safeguards such as password hashing, scoped roles, and
              separation of web and API responsibilities. Security also depends on your patching,
              network controls, backups, secrets management, and physical access to hardware. The
              operator is responsible for those layers.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-white">8. Retention and deletion</h2>
            <p>
              Retention is governed by how you operate the instance: backups, database exports, and
              file lifecycle rules are under operator control. Features such as soft-delete or job
              cleanup behave as implemented in your version of the software; review release notes
              and documentation for specifics.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-white">9. Your rights</h2>
            <p>
              Where privacy laws grant individuals rights (access, correction, deletion, etc.),
              the operator of your instance is usually responsible for honoring requests. If you
              are the operator, ensure you can respond to your users in line with your jurisdiction.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-white">10. Changes to this policy</h2>
            <p>
              Operators may customize or replace this policy text for their deployment. If you ship
              Arciin to others, publish your effective date and change process. Application updates
              may introduce new features that process additional categories of data; review release
              notes when upgrading.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-white">11. Contact</h2>
            <p>
              For questions about a specific instance, contact that instance&apos;s operator. For
              questions about the Arciin software itself, use the contact or issue tracker
              maintained by your software distributor or upstream project, if applicable.
            </p>
          </section>
        </div>

        <footer className="border-t border-white/10 pt-8 text-xs text-zinc-500">
          <p>Effective as of the date shown in your deployment documentation unless you replace this page.</p>
        </footer>
      </article>
    </main>
  )
}
