#!/usr/bin/env bash
#
# Isolated Docker smoke test for Arciin.
#
# Builds the hardened images and brings the FULL stack up as a throwaway
# project (`arciin-test`) on its own port, network, volumes and data dir — it
# never touches a running PM2 instance or its data. Then it verifies the
# security hardening (non-root containers, Redis auth, unpublished Postgres,
# auth-gated imports, security headers).
#
# Usage:
#   bash scripts/docker-smoke-test.sh          # build + up + verify (leaves it running)
#   bash scripts/docker-smoke-test.sh --down   # tear everything down (removes test volumes)
#
# Needs Docker access: either your user is in the `docker` group, or run with sudo.

set -uo pipefail

cd "$(dirname "$0")/.."
ROOT="$(pwd)"

PROJECT="arciin-test"
ENV_FILE="${ROOT}/.env.docker.test"
OVERRIDE="${ROOT}/docker-compose.smoke.yml"
HTTP_PORT="${ARCIIN_HTTP_PORT:-8087}"
DATA_DIR="${ARCIIN_TEST_DATA_DIR:-/srv/arciin-storage/arciin-docker-test}"

# uid/gid the containers run as (must own the bind-mounted data dir). Prefer the
# invoking user even when run under sudo.
PUID="${SUDO_UID:-$(id -u)}"
PGID="${SUDO_GID:-$(id -g)}"

GREEN="\033[0;32m"; RED="\033[0;31m"; YEL="\033[0;33m"; DIM="\033[2m"; RST="\033[0m"
pass() { echo -e "  ${GREEN}PASS${RST}  $1"; }
fail() { echo -e "  ${RED}FAIL${RST}  $1"; FAILED=$((FAILED + 1)); }
info() { echo -e "  ${DIM}$1${RST}"; }
FAILED=0

gen() { openssl rand -hex "${1:-24}" 2>/dev/null || head -c "${1:-24}" /dev/urandom | xxd -p -c 96; }

COMPOSE=(docker compose -p "$PROJECT" --env-file "$ENV_FILE" -f docker-compose.yml -f "$OVERRIDE")

# ── Preflight ────────────────────────────────────────────────────────────────
if ! docker ps >/dev/null 2>&1; then
  echo -e "${RED}Cannot reach the Docker daemon.${RST}"
  echo "  Add your user to the docker group:  sudo usermod -aG docker \$USER  (then re-login)"
  echo "  …or run this script with sudo:       sudo bash scripts/docker-smoke-test.sh"
  exit 1
fi

# ── Teardown mode ────────────────────────────────────────────────────────────
if [[ "${1:-}" == "--down" ]]; then
  echo "Tearing down the $PROJECT stack and its volumes…"
  [[ -f "$OVERRIDE" ]] && "${COMPOSE[@]}" down -v --remove-orphans || docker compose -p "$PROJECT" down -v --remove-orphans
  rm -f "$OVERRIDE"
  echo "Done. (Left $ENV_FILE and $DATA_DIR in place; delete them manually if you want.)"
  exit 0
fi

# ── Isolated env file (generated once, reused on re-runs) ─────────────────────
if [[ ! -f "$ENV_FILE" ]]; then
  echo "Generating isolated test env → $ENV_FILE"
  cat > "$ENV_FILE" <<EOF
NODE_ENV=production
ARCIIN_HOST_DATA_DIR=${DATA_DIR}
ARCIIN_DATA_DIR=/data/arciin
ARCIIN_HTTP_PORT=${HTTP_PORT}
ARCIIN_PUID=${PUID}
ARCIIN_PGID=${PGID}
ARCIIN_SETUP_TOKEN=$(gen 24)
SESSION_SECRET=$(gen 32)
ARCIIN_ENCRYPTION_KEY=$(gen 32)
POSTGRES_PASSWORD=$(gen 24)
REDIS_PASSWORD=$(gen 24)
SESSION_COOKIE_NAME=arciin_session
ARCIIN_PUBLIC_URL=http://localhost:${HTTP_PORT}
ARCIIN_API_URL=http://api:4000
NEXT_PUBLIC_API_BASE_URL=/api
NEXT_PUBLIC_SOCKET_URL=
MAX_UPLOAD_SIZE_MB=20480
UPLOAD_RATE_LIMIT_PER_MINUTE=500
ARCIIN_WORKER_CONCURRENCY=2
EOF
  chmod 600 "$ENV_FILE"
else
  info "Reusing existing $ENV_FILE"
fi

# The base compose reads env_file: .env — for an isolated test we append our
# test file so its secrets win (compose merges env_file lists; later wins).
cat > "$OVERRIDE" <<EOF
# Generated by docker-smoke-test.sh — appends the isolated env into the
# api/worker containers so the test uses its own secrets, not a live .env.
services:
  api:
    env_file:
      - .env.docker.test
  worker:
    env_file:
      - .env.docker.test
EOF

set -a; source "$ENV_FILE"; set +a

echo ""
echo "Isolated test stack:"
echo "  project     $PROJECT"
echo "  url         http://localhost:${HTTP_PORT}"
echo "  data dir    ${DATA_DIR}"
echo "  runs as     uid ${PUID}:${PGID} (non-root)"
echo ""

# ── Prepare the bind-mount data dir with the right owner ─────────────────────
mkdir -p "$DATA_DIR"
chown -R "${PUID}:${PGID}" "$DATA_DIR" 2>/dev/null || info "(could not chown $DATA_DIR — continuing)"

# ── Build + up ───────────────────────────────────────────────────────────────
echo "Building images (first run pulls base layers — can take several minutes)…"
if ! "${COMPOSE[@]}" build; then echo -e "${RED}Build failed.${RST}"; exit 1; fi

echo "Starting the stack…"
if ! "${COMPOSE[@]}" up -d; then echo -e "${RED}Startup failed.${RST}"; "${COMPOSE[@]}" logs --tail 40; exit 1; fi

# ── Wait for API health ──────────────────────────────────────────────────────
echo -n "Waiting for the API to become healthy"
HEALTHY=0
for _ in $(seq 1 60); do
  if curl -fsS "http://localhost:${HTTP_PORT}/api/health" >/dev/null 2>&1; then HEALTHY=1; break; fi
  echo -n "."; sleep 3
done
echo ""
if [[ "$HEALTHY" != "1" ]]; then
  echo -e "${RED}API never became healthy. Recent logs:${RST}"
  "${COMPOSE[@]}" logs --tail 60 api
  exit 1
fi

# ── Verifications ────────────────────────────────────────────────────────────
echo ""
echo "Running security + smoke checks:"

# 1. Web + API reachable through Caddy
code=$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:${HTTP_PORT}/login")
[[ "$code" == "200" || "$code" == "307" || "$code" == "302" ]] && pass "Web UI reachable via Caddy ($code)" || fail "Web UI returned $code"
curl -fsS "http://localhost:${HTTP_PORT}/api/health" >/dev/null 2>&1 && pass "API /health OK" || fail "API health failed"

# 2. Containers run as non-root
for svc in api worker; do
  uid=$("${COMPOSE[@]}" exec -T "$svc" id -u 2>/dev/null | tr -d '\r')
  if [[ -n "$uid" && "$uid" != "0" ]]; then pass "$svc container runs as non-root (uid $uid)"; else fail "$svc container uid is '$uid' (want non-root)"; fi
done

# 3. Redis requires authentication
noauth=$("${COMPOSE[@]}" exec -T redis redis-cli ping 2>&1 | tr -d '\r')
if echo "$noauth" | grep -qi "NOAUTH"; then pass "Redis rejects unauthenticated PING (auth enforced)"; else fail "Redis answered PING without a password: '$noauth'"; fi
withauth=$("${COMPOSE[@]}" exec -T redis redis-cli -a "$REDIS_PASSWORD" ping 2>/dev/null | tr -d '\r')
[[ "$withauth" == "PONG" ]] && pass "Redis accepts the configured password" || fail "Redis auth with password failed: '$withauth'"

# 4. Postgres is NOT published to the host
pgport=$("${COMPOSE[@]}" port postgres 5432 2>/dev/null)
[[ -z "$pgport" ]] && pass "Postgres has no host-published port (internal only)" || fail "Postgres is exposed on the host: $pgport"

# 5. Import endpoint requires authentication (SSRF surface is gated)
imp=$(curl -s -o /dev/null -w "%{http_code}" -X POST "http://localhost:${HTTP_PORT}/api/imports" -H "content-type: application/json" -d '{"url":"http://169.254.169.254/"}')
[[ "$imp" == "401" ]] && pass "URL import requires auth (401 unauthenticated)" || fail "Unauthenticated import returned $imp (want 401)"

# 6. Security headers present (helmet)
hdrs=$(curl -sI "http://localhost:${HTTP_PORT}/api/health")
echo "$hdrs" | grep -qi "x-content-type-options: nosniff" && pass "X-Content-Type-Options: nosniff present" || fail "nosniff header missing"
echo "$hdrs" | grep -qi "content-security-policy" && pass "Content-Security-Policy present" || info "CSP not on /health (set on app routes)"

# 7. Media pipeline tools present in the worker image
for tool in ffmpeg yt-dlp gallery-dl pdftoppm; do
  if "${COMPOSE[@]}" exec -T worker sh -c "command -v $tool" >/dev/null 2>&1; then
    pass "worker has $tool"
  else
    fail "worker image is missing $tool (media jobs/imports will fail)"
  fi
done

# ── Summary ──────────────────────────────────────────────────────────────────
echo ""
if [[ "$FAILED" == "0" ]]; then
  echo -e "${GREEN}All checks passed.${RST}"
else
  echo -e "${RED}${FAILED} check(s) failed — see above.${RST}"
fi
echo ""
echo "The stack is running so you can click through it:"
echo -e "  ${YEL}http://localhost:${HTTP_PORT}${RST}   (claim with setup token from ${ENV_FILE})"
echo -e "  setup token:  ${DIM}$(grep '^ARCIIN_SETUP_TOKEN=' "$ENV_FILE" | cut -d= -f2)${RST}"
echo ""
echo "Logs:      ${COMPOSE[*]} logs -f"
echo "Tear down: bash scripts/docker-smoke-test.sh --down"
exit "$FAILED"
